### ISSUE TITLE
Digito conta corrente Santander

### ISSUE THREAD

**Issue by mvianello** [moip/bank-account-validator-js#4]
Estou tentando validar o campo digito da conta corrente do banco santander. A validação permite qualque número nesse campo... não seria o caso de funcionar como o Itau e Bradesco que somente permitem um valor especifico no campo de digito da conta corrente? Quando tento alterar o digito do Itau, recebo o erro "- Dígito da conta não corresponde ao número da conta/agência preenchido", e gostaria de receber tambem quando o banco for Santander... algum jeito simples de aplicar essa validacao tbm?

**Comment by somentelucas** [comment]
Oi @mvianello, no momento não é possível. Para o [Itaú](https://github.com/moip/bank-account-validator-js/blob/master/src/itau_check_number_calculator.js), [Banco do Brasil](https://github.com/moip/bank-account-validator-js/blob/master/src/banco_do_brasil_check_number_calculator.js) e [Bradesco](https://github.com/moip/bank-account-validator-js/blob/master/src/bradesco_check_number_calculator.js) existe um arquivo que conhece a lógica de comparação do dígito com a conta bancária e faz essa validação. Para o banco Santander, nós não conhecemos essa validação, por isso a mensagem de erro é mais genérica.

**Comment by elton182** [comment]
@somentelucas consegui encontrar uma solução para o santander, até criei um gist

vamos implementar isso e mandar um PR ok?

**Comment by elton182** [comment]
https://gist.github.com/elton182/f7ac5fe480ad8d6ca356aa0700a59b47

**Comment by rodribeze** [comment]
Legal elton, segue melhorias em php.

`function validarContaSantander($numero_agencia,$numero_conta){

   $numero = preg_replace('/[^0-9]/','',$numero_agencia);
   $numero .= str_pad($numero_conta,10,"0",STR_PAD_LEFT);

   $multiplicadores = ['9','7','3','1','0','0','9','7','1','3','1','9','7','3'];

   $total = 0;

   foreach(str_split((string)$numero) as $k => $n){

      $multiplicadores[$k] = $n * $multiplicadores[$k];

      if($multiplicadores[$k] > 9){
         $multiplicadores[$k] = substr($multiplicadores[$k],1);
      }

      $total += (int)$multiplicadores[$k];

   }

   if($total > 9){
      $total = substr($total,1);
   }

   return 10 - $total;

}`
